apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app-deployment
  labels:
    app: demo-voting-app
spec:
  replicas: 2
  template:
    metadata:
      name: result-app-pod
      labels:
        name: result-app-pod
        app: demo-voting-app
    spec:
      containers:
        - image: dockersamples/examplevotingapp_result
          name: result-app-pod
          ports:
            - containerPort: 80
  selector:
    matchLabels:
      name: result-app-pod
      app: demo-voting-app
      
    