apiVersion: v1
kind: Service
metadata:
  name: voting-app-service
  labels:
    name: voting-app-service
    app: demo-voting-app
spec:
  ports:
  - port:  80
    targetPort:  80
  selector:
    name: voting-app-pod
    app: demo-voting-app
  type: LoadBalancer