apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-deployment
  labels:
    app: demo-voting-app
spec:
  replicas: 3
  template:
    metadata:
      name: voting-app-pod
      labels:
        name: voting-app-pod
        app: demo-voting-app
    spec:
      containers:
        - image: dockersamples/examplevotingapp_vote
          name: voting-app-pod
          ports:
            - containerPort: 80
  selector:
    matchLabels:
      name: voting-app-pod
      app: demo-voting-app
      
    